# Generated by Django 4.2.6 on 2023-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioIngresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='es_personal',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='esta_activa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultimo_login',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets'),
        ),
    ]
